### ISSUE TITLE
CS generated code does not compile on the go

### ISSUE THREAD

**Issue by Yooooomi** [Hetarnam/Dofus2ProtocolGenerator#1]
I just tried your project this morning, and I can get the base CS generated code to work properly.
It seems like he doesn't find the Namespace you're using at the top of your files

![image](https://user-images.githubusercontent.com/17204739/87425024-46883f80-c5dd-11ea-9ba7-6456c4cecc8d.png)

I assume that all the missing types are coming from this namespace but I dont know where to find it.

Thanks for the help you can bring me, nice project btw :)

**Comment by Grandnainconnu** [comment]
Salut !

Dans les fichiers templates tu as tout, il faut bien évidemment les lier à ton code, pas au mien !
Ici les endroits que tu dois modifier :
![capture d'écran](https://user-images.githubusercontent.com/4025637/87428288-52d7c100-c60c-11ea-919e-76802fd3f86b.png)

**Comment by Yooooomi** [comment]
Okay thanks for the answer, now I'm having more questions about `configuration.php`

What is the use of having two elements in the array such as short and ushort ? What are the differences between `writeShort` and `writeVarShort` ?

```
const WRITE_TYPE_MAPPER = [
    'byte' => [ 'WriteByte' ],
    'long' => [ 'WriteLong' ],
    'uint' => [ 'WriteUInt' ],
    'int' => [ 'WriteInt' ],
    'short' => [ 'writeShort', 'writeVarShort' ],
    'ushort' => [ 'writeUShort', 'writeVarUShort' ],
    'string' => [ 'writeUTF' ],
    'bool' => [ 'writeBoolean' ],
    'float' => [ 'writeFloat' ],
    'char' => [ 'WriteChar' ],
    'double' => [ 'WriteDouble' ]
];
```

When I edit the `WRITE_TYPE_MAPPER` and `READ_METHOD_MAPPER` variables to look like:

```
const WRITE_TYPE_MAPPER = [
    'byte' => [ 'writeByteeee' ],
    'long' => [ 'writeVarLong' ],
    'uint' => [ 'writeVarUInt', 'writeUInt' ],
    'int' => [ 'writeInt', 'writeVarInt' ],
    'short' => [ 'writeShort', 'writeVarShort' ],
    'ushort' => [ 'writeUShort', 'writeVarUShort' ],
    'string' => [ 'writeUTF' ],
    'bool' => [ 'writeBoolean' ],
    'float' => [ 'writeFloat' ],
    'char' => [ 'writeChar' ],
    'double' => [ 'writeDouble' ]
];

const READ_METHOD_MAPPER = [
    'writeByteeee' => 'readByteeeee',
    'writeVarLong' => 'readVarLong',
    'writeVarUInt' => 'readVarUInt',
    'writeVarInt' => 'readVarInt',
    'writeVarShort' => 'readVarShort',
    'writeVarUShort' => 'readVarUShort',
    'writeUShort' => 'readUShort',
    'writeShort' => 'readShort',
    'writeInt' => 'readInt',
    'writeUInt' => 'readUInt',
    'writeUTF' => 'readUTF',
    'writeBoolean' => 'readBoolean',
    'writeFloat' => 'readFloat',
    'writeChar' => 'readChar',
    'writeDouble' => 'readDouble'
];
```

Why is the WriteByte function used still WriteByte and not `writeByteeee` ?

![image](https://user-images.githubusercontent.com/17204739/87437379-86a3ee00-c5ee-11ea-89a0-f5e3af837c73.png)

Thanks for all the answers you'll bring me ^^
